/**
 * Seed ~30 realistic test candidates into the Candidate table.
 *
 * Distribution: 60% Italian, 30% foreign (N. Africa / E. Europe / S. America),
 * 10% mixed. Operational profiles: cleaning, kitchen, manual labor, drivers,
 * supermarket, metalworking.
 *
 * Run: set -a && source .env.local && set +a && pnpm tsx scripts/seed-candidates.ts
 *
 * Idempotent: uses upsert keyed on (poolId, externalId).
 * Override target pool: TARGET_POOL_SLUG=159244 pnpm tsx scripts/seed-candidates.ts
 */
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: process.env["DATABASE_URL"] ?? "" }),
});

interface Seed {
  externalId: string;
  firstName: string;
  lastName: string;
  birthday: string; // YYYY-MM-DD
  countryOfOrigin: string;
  address: string;
  phone: string;
  workingPermit: boolean | null;
  meanOfTransport: string;
  drivingLicense: boolean | null;
  educationAndTraining: string[];
  workExperience: string[];
  skillsAndCompetences: string[]; // 3-4 each
  language: string;
  additionalLanguages: string[];
  italianLevel: string | null;
  desiredJob: string;
  partTimePreference: boolean;
  preferredLocation: string;
  jobConstraints: string | null;
  hasDesiredJobExperience: string;
  sourceOrganization: string;
  channel: "telegram" | "whatsapp";
}

// ---------------------------------------------------------------------------
// 18 Italian candidates
// ---------------------------------------------------------------------------
const italians: Seed[] = [
  {
    externalId: "seed-it-001",
    firstName: "Marco",
    lastName: "Rossi",
    birthday: "1985-04-12",
    countryOfOrigin: "Italia",
    address: "Via Garibaldi 14, Milano",
    phone: "+39 333 1112201",
    workingPermit: null,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma di perito meccanico - ITIS Feltrinelli, Milano (2004)",
      "Corso saldatura MIG/MAG - CFP Lombardia (2010)",
    ],
    workExperience: [
      "Saldatore - Officine Meccaniche Brambilla srl, Sesto San Giovanni (2018-2024)",
      "Carrellista - Magazzino logistico Milano Smistamento (2010-2018)",
    ],
    skillsAndCompetences: [
      "Saldatura MIG/MAG e TIG",
      "Lettura disegno meccanico",
      "Patentino muletto",
      "Manutenzione macchinari",
    ],
    language: "Italiano",
    additionalLanguages: ["Inglese A2"],
    italianLevel: "Madrelingua",
    desiredJob: "Saldatore o operaio metalmeccanico",
    partTimePreference: false,
    preferredLocation: "Milano e hinterland nord",
    jobConstraints: "No turni notturni",
    hasDesiredJobExperience: "Sì, oltre 10 anni",
    sourceOrganization: "Cooperativa La Strada - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-002",
    firstName: "Giulia",
    lastName: "Ferrari",
    birthday: "1992-09-23",
    countryOfOrigin: "Italia",
    address: "Via Dante 8, Bologna",
    phone: "+39 340 2231104",
    workingPermit: null,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma alberghiero - IPSSAR Scappi, Bologna (2011)",
      "Corso HACCP base (2019)",
    ],
    workExperience: [
      "Cuoca di partita - Trattoria del Rosso, Bologna (2020-2024)",
      "Aiuto cuoca - Hotel Centrale, Rimini (stagionale 2015-2019)",
    ],
    skillsAndCompetences: [
      "Cucina tradizionale emiliana",
      "Gestione mise en place",
      "Conoscenza HACCP",
      "Lavoro sotto pressione",
    ],
    language: "Italiano",
    additionalLanguages: ["Inglese B1"],
    italianLevel: "Madrelingua",
    desiredJob: "Cuoca o aiuto cuoca",
    partTimePreference: false,
    preferredLocation: "Bologna città",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 9 anni",
    sourceOrganization: "APL Bologna - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-003",
    firstName: "Antonio",
    lastName: "Esposito",
    birthday: "1978-01-30",
    countryOfOrigin: "Italia",
    address: "Via Toledo 145, Napoli",
    phone: "+39 328 4459712",
    workingPermit: null,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Licenza media - Scuola Media Statale Pascoli, Napoli (1992)",
      "CQC trasporto merci - Autoscuola Napoli (rinnovo 2023)",
    ],
    workExperience: [
      "Autista patente C+E - Trasporti Vesuvio srl (2010-2024)",
      "Magazziniere - GDO Napoli Centro (2003-2010)",
    ],
    skillsAndCompetences: [
      "Guida autoarticolato",
      "Cronotachigrafo digitale",
      "Carico e scarico merci",
      "Conoscenza rete autostradale Centro-Sud",
    ],
    language: "Italiano",
    additionalLanguages: [],
    italianLevel: "Madrelingua",
    desiredJob: "Autista patente C/E",
    partTimePreference: false,
    preferredLocation: "Campania, disponibile trasferte",
    jobConstraints: "Preferenza tratte diurne",
    hasDesiredJobExperience: "Sì, 14 anni",
    sourceOrganization: "Cooperativa Lavoro Sud - WhatsApp",
    channel: "whatsapp",
  },
  {
    externalId: "seed-it-004",
    firstName: "Chiara",
    lastName: "Conti",
    birthday: "1996-06-18",
    countryOfOrigin: "Italia",
    address: "Via Mazzini 22, Torino",
    phone: "+39 347 1102233",
    workingPermit: null,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma liceo scientifico - Liceo Galileo Ferraris, Torino (2015)",
    ],
    workExperience: [
      "Cassiera - Esselunga Torino Lingotto (2019-2024)",
      "Commessa - Profumeria Limoni, Torino (2017-2019)",
    ],
    skillsAndCompetences: [
      "Uso casse self-service",
      "Gestione resi e reclami",
      "Rifornimento scaffali",
      "Pacchetto Office base",
    ],
    language: "Italiano",
    additionalLanguages: ["Inglese B1", "Spagnolo A2"],
    italianLevel: "Madrelingua",
    desiredJob: "Cassiera o addetta vendita GDO",
    partTimePreference: true,
    preferredLocation: "Torino centro",
    jobConstraints: "Preferenza part-time mattino",
    hasDesiredJobExperience: "Sì, 5 anni",
    sourceOrganization: "Cooperativa Torino Solidale - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-005",
    firstName: "Davide",
    lastName: "Greco",
    birthday: "1990-11-04",
    countryOfOrigin: "Italia",
    address: "Via Etnea 78, Catania",
    phone: "+39 320 9988120",
    workingPermit: null,
    meanOfTransport: "Motorino",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma istituto tecnico - Catania (2009)",
      "Corso barman AIBES (2018)",
    ],
    workExperience: [
      "Barman - Lungomare Lounge Bar, Catania (2019-2024)",
      "Cameriere - Hotel Mediterraneo, Taormina (stagionale 2014-2018)",
    ],
    skillsAndCompetences: [
      "Preparazione cocktail IBA",
      "Caffetteria e latte art",
      "Gestione cassa",
      "Inglese turistico",
    ],
    language: "Italiano",
    additionalLanguages: ["Inglese B1"],
    italianLevel: "Madrelingua",
    desiredJob: "Barman o cameriere",
    partTimePreference: false,
    preferredLocation: "Catania e provincia",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 10 anni",
    sourceOrganization: "Cooperativa Sicilia Attiva - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-006",
    firstName: "Federica",
    lastName: "Marini",
    birthday: "1988-02-14",
    countryOfOrigin: "Italia",
    address: "Via Veneto 5, Roma",
    phone: "+39 339 4477812",
    workingPermit: null,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma servizi sociosanitari - IPS Roma (2007)",
      "Corso assistenza domiciliare (2013)",
    ],
    workExperience: [
      "Addetta pulizie sanitarie - Ospedale San Camillo, Roma (2018-2024)",
      "Collaboratrice domestica - privato (2010-2018)",
    ],
    skillsAndCompetences: [
      "Pulizie professionali e sanificazione",
      "Conoscenza prodotti chimici e DPI",
      "Gestione scope a carrello",
      "Attenzione al dettaglio",
    ],
    language: "Italiano",
    additionalLanguages: [],
    italianLevel: "Madrelingua",
    desiredJob: "Addetta pulizie o sanificazione",
    partTimePreference: true,
    preferredLocation: "Roma centro/EUR",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 14 anni",
    sourceOrganization: "Caritas Roma - WhatsApp",
    channel: "whatsapp",
  },
  {
    externalId: "seed-it-007",
    firstName: "Luca",
    lastName: "Bianchi",
    birthday: "1983-07-29",
    countryOfOrigin: "Italia",
    address: "Via Indipendenza 33, Verona",
    phone: "+39 345 1245678",
    workingPermit: null,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Qualifica professionale operatore meccanico - CFP Verona (2002)",
    ],
    workExperience: [
      "Operaio addetto linea - Stabilimento alimentare Verona (2015-2024)",
      "Magazziniere - Logistica Pedemontana (2005-2015)",
    ],
    skillsAndCompetences: [
      "Conduzione muletto frontale e laterale",
      "Picking e packing",
      "Gestione bolle e DDT",
      "Lavoro su 3 turni",
    ],
    language: "Italiano",
    additionalLanguages: [],
    italianLevel: "Madrelingua",
    desiredJob: "Magazziniere o carrellista",
    partTimePreference: false,
    preferredLocation: "Verona e basso Veneto",
    jobConstraints: "Disponibile a turni anche notturni",
    hasDesiredJobExperience: "Sì, oltre 15 anni",
    sourceOrganization: "Cooperativa Veneto Lavoro - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-008",
    firstName: "Sara",
    lastName: "Romano",
    birthday: "1999-12-02",
    countryOfOrigin: "Italia",
    address: "Via dei Mille 12, Bari",
    phone: "+39 366 2233445",
    workingPermit: null,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma istituto alberghiero - IPSSAR Perotti, Bari (2018)",
    ],
    workExperience: [
      "Cameriera di sala - Ristorante Borgo Antico, Bari (2020-2024)",
      "Hostess fiere - eventi vari, Bari (2018-2020)",
    ],
    skillsAndCompetences: [
      "Servizio al tavolo",
      "Conoscenza cucina pugliese",
      "Inglese B2 fluente",
      "Gestione clienti stranieri",
    ],
    language: "Italiano",
    additionalLanguages: ["Inglese B2", "Francese A2"],
    italianLevel: "Madrelingua",
    desiredJob: "Cameriera o hostess",
    partTimePreference: true,
    preferredLocation: "Bari città",
    jobConstraints: "Preferenza orario serale",
    hasDesiredJobExperience: "Sì, 4 anni",
    sourceOrganization: "Cooperativa Puglia Insieme - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-009",
    firstName: "Roberto",
    lastName: "Galli",
    birthday: "1975-05-10",
    countryOfOrigin: "Italia",
    address: "Via dei Tigli 7, Padova",
    phone: "+39 349 8765432",
    workingPermit: null,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma geometra - ITG Padova (1994)",
      "Corso sicurezza cantieri 16h (2022)",
    ],
    workExperience: [
      "Muratore - Edilizia Galli & Figli (2010-2024)",
      "Operaio cantiere - varie imprese edili Veneto (1996-2010)",
    ],
    skillsAndCompetences: [
      "Posa in opera intonaci e cartongesso",
      "Lettura disegni tecnici",
      "Uso ponteggi in sicurezza",
      "Coordinamento piccola squadra",
    ],
    language: "Italiano",
    additionalLanguages: [],
    italianLevel: "Madrelingua",
    desiredJob: "Muratore o caposquadra cantiere",
    partTimePreference: false,
    preferredLocation: "Padova e Vicenza",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, oltre 25 anni",
    sourceOrganization: "Cooperativa Edile Veneta - WhatsApp",
    channel: "whatsapp",
  },
  {
    externalId: "seed-it-010",
    firstName: "Elena",
    lastName: "Lombardi",
    birthday: "1994-08-21",
    countryOfOrigin: "Italia",
    address: "Via XX Settembre 44, Genova",
    phone: "+39 351 4488991",
    workingPermit: null,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma istituto tecnico commerciale - Genova (2013)",
    ],
    workExperience: [
      "Addetta vendita - Coop Liguria, Genova Sampierdarena (2017-2024)",
      "Commessa - panetteria di quartiere, Genova (2014-2017)",
    ],
    skillsAndCompetences: [
      "Rifornimento scaffali e rotazione FIFO",
      "Gestione reparto ortofrutta",
      "Conoscenza etichettatura prodotti",
      "Cassa e POS",
    ],
    language: "Italiano",
    additionalLanguages: ["Inglese A2"],
    italianLevel: "Madrelingua",
    desiredJob: "Addetta supermercato",
    partTimePreference: true,
    preferredLocation: "Genova ovest",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 7 anni",
    sourceOrganization: "Coop Liguria - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-011",
    firstName: "Stefano",
    lastName: "Costa",
    birthday: "1987-03-17",
    countryOfOrigin: "Italia",
    address: "Via Manzoni 91, Firenze",
    phone: "+39 338 5566123",
    workingPermit: null,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma istituto professionale - Firenze (2006)",
      "CQC trasporto persone - Autoscuola Toscana (rinnovo 2024)",
    ],
    workExperience: [
      "Autista NCC - Cooperativa Taxi Firenze (2018-2024)",
      "Autista pulmini scolastici - Comune di Sesto Fiorentino (2012-2018)",
    ],
    skillsAndCompetences: [
      "Patente D + CQC persone",
      "Conoscenza area metropolitana fiorentina",
      "Gestione clientela turistica",
      "Inglese turistico base",
    ],
    language: "Italiano",
    additionalLanguages: ["Inglese A2"],
    italianLevel: "Madrelingua",
    desiredJob: "Autista NCC o pulmini",
    partTimePreference: false,
    preferredLocation: "Firenze e provincia",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 12 anni",
    sourceOrganization: "Cooperativa Trasporti Toscana - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-012",
    firstName: "Martina",
    lastName: "Caruso",
    birthday: "2001-10-09",
    countryOfOrigin: "Italia",
    address: "Via Libertà 23, Palermo",
    phone: "+39 327 7788990",
    workingPermit: null,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma servizi commerciali - IPS Palermo (2020)",
    ],
    workExperience: [
      "Aiuto cuoca - Friggitoria del Porto, Palermo (2022-2024)",
      "Cameriera estiva - Lido Mondello (2019-2021)",
    ],
    skillsAndCompetences: [
      "Cucina siciliana di strada",
      "Frittura e gestione fritti",
      "Pulizia cucina e HACCP",
      "Resistenza fisica",
    ],
    language: "Italiano",
    additionalLanguages: [],
    italianLevel: "Madrelingua",
    desiredJob: "Aiuto cuoca o cameriera",
    partTimePreference: false,
    preferredLocation: "Palermo centro",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 3 anni",
    sourceOrganization: "Cooperativa Sicilia Attiva - WhatsApp",
    channel: "whatsapp",
  },
  {
    externalId: "seed-it-013",
    firstName: "Simone",
    lastName: "Rinaldi",
    birthday: "1980-09-15",
    countryOfOrigin: "Italia",
    address: "Via Emilia 102, Reggio Emilia",
    phone: "+39 340 9911223",
    workingPermit: null,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Qualifica meccanico - CFP Reggio Emilia (1999)",
    ],
    workExperience: [
      "Manutentore meccanico - Stabilimento ceramico Sassuolo (2005-2024)",
    ],
    skillsAndCompetences: [
      "Manutenzione meccanica linee produttive",
      "Diagnosi guasti",
      "Saldatura ad elettrodo",
      "Lettura schemi pneumatici",
    ],
    language: "Italiano",
    additionalLanguages: [],
    italianLevel: "Madrelingua",
    desiredJob: "Manutentore meccanico",
    partTimePreference: false,
    preferredLocation: "Reggio Emilia / Modena",
    jobConstraints: "No spostamenti fuori regione",
    hasDesiredJobExperience: "Sì, 19 anni",
    sourceOrganization: "Cooperativa Emilia Lavoro - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-014",
    firstName: "Valentina",
    lastName: "Moretti",
    birthday: "1991-12-30",
    countryOfOrigin: "Italia",
    address: "Via Roma 56, Ancona",
    phone: "+39 366 5544332",
    workingPermit: null,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma alberghiero - IPSSAR Panzini, Senigallia (2010)",
      "Corso pasticceria base - Cast Alimenti (2017)",
    ],
    workExperience: [
      "Pasticcera - Pasticceria Centrale Ancona (2018-2024)",
      "Aiuto cuoca - Hotel Conero, Numana (stagionale 2012-2018)",
    ],
    skillsAndCompetences: [
      "Pasticceria classica italiana",
      "Lievitati e impasti",
      "Decorazione torte",
      "Gestione laboratorio",
    ],
    language: "Italiano",
    additionalLanguages: ["Inglese A2"],
    italianLevel: "Madrelingua",
    desiredJob: "Pasticcera o aiuto cuoca",
    partTimePreference: false,
    preferredLocation: "Ancona e riviera",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 12 anni",
    sourceOrganization: "Cooperativa Marche Lavoro - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-015",
    firstName: "Paolo",
    lastName: "Russo",
    birthday: "1972-04-25",
    countryOfOrigin: "Italia",
    address: "Via Diaz 14, Pescara",
    phone: "+39 328 6677889",
    workingPermit: null,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma perito industriale - ITIS Pescara (1991)",
    ],
    workExperience: [
      "Operaio specializzato - Stabilimento metalmeccanico Chieti (2000-2024)",
    ],
    skillsAndCompetences: [
      "Tornitura tradizionale e CNC",
      "Fresatura",
      "Controllo qualità con calibri e micrometri",
      "Lettura disegni meccanici complessi",
    ],
    language: "Italiano",
    additionalLanguages: [],
    italianLevel: "Madrelingua",
    desiredJob: "Tornitore o operatore CNC",
    partTimePreference: false,
    preferredLocation: "Pescara / Chieti",
    jobConstraints: "Disponibile turni",
    hasDesiredJobExperience: "Sì, 24 anni",
    sourceOrganization: "Cooperativa Abruzzo Lavoro - WhatsApp",
    channel: "whatsapp",
  },
  {
    externalId: "seed-it-016",
    firstName: "Alessia",
    lastName: "De Luca",
    birthday: "1998-07-07",
    countryOfOrigin: "Italia",
    address: "Via San Lorenzo 9, Cagliari",
    phone: "+39 351 1122334",
    workingPermit: null,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma servizi commerciali - Cagliari (2017)",
      "Corso operatrice sociosanitaria OSS (2021)",
    ],
    workExperience: [
      "OSS - Casa di riposo Sant'Anna, Cagliari (2022-2024)",
      "Babysitter - privato (2018-2022)",
    ],
    skillsAndCompetences: [
      "Assistenza anziani non autosufficienti",
      "Igiene della persona",
      "Compilazione cartelle",
      "Empatia e ascolto",
    ],
    language: "Italiano",
    additionalLanguages: ["Inglese A2"],
    italianLevel: "Madrelingua",
    desiredJob: "OSS o assistente anziani",
    partTimePreference: false,
    preferredLocation: "Cagliari",
    jobConstraints: "Disponibile turni notturni",
    hasDesiredJobExperience: "Sì, 2 anni",
    sourceOrganization: "Cooperativa Sardegna Solidale - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-017",
    firstName: "Giovanni",
    lastName: "Ricci",
    birthday: "1989-01-19",
    countryOfOrigin: "Italia",
    address: "Via Po 88, Trieste",
    phone: "+39 339 9988776",
    workingPermit: null,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma perito logistico - Trieste (2008)",
    ],
    workExperience: [
      "Capo turno magazzino - Logistica Porto di Trieste (2017-2024)",
      "Magazziniere - Centro distribuzione GDO (2010-2017)",
    ],
    skillsAndCompetences: [
      "Coordinamento squadra magazzino (8 persone)",
      "Gestione WMS SAP",
      "Controllo inventari",
      "Patentino muletto e transpallet elettrico",
    ],
    language: "Italiano",
    additionalLanguages: ["Inglese B1", "Sloveno A2"],
    italianLevel: "Madrelingua",
    desiredJob: "Capo turno magazzino",
    partTimePreference: false,
    preferredLocation: "Trieste e Monfalcone",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 14 anni",
    sourceOrganization: "Cooperativa FVG Lavoro - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-it-018",
    firstName: "Camilla",
    lastName: "Fontana",
    birthday: "2000-05-28",
    countryOfOrigin: "Italia",
    address: "Via Solferino 7, Brescia",
    phone: "+39 347 3344556",
    workingPermit: null,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma servizi sociali - IPS Brescia (2019)",
    ],
    workExperience: [
      "Addetta pulizie uffici - Cooperativa Pulizie Bresciane (2021-2024)",
    ],
    skillsAndCompetences: [
      "Pulizie uffici e aree comuni",
      "Uso macchine lavasciuga",
      "Sanificazione bagni e cucine",
      "Affidabilità e puntualità",
    ],
    language: "Italiano",
    additionalLanguages: ["Inglese A2"],
    italianLevel: "Madrelingua",
    desiredJob: "Addetta pulizie",
    partTimePreference: true,
    preferredLocation: "Brescia città",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 3 anni",
    sourceOrganization: "Cooperativa Brescia Insieme - Telegram",
    channel: "telegram",
  },
];

// ---------------------------------------------------------------------------
// 4 N. African candidates
// ---------------------------------------------------------------------------
const northAfricans: Seed[] = [
  {
    externalId: "seed-na-001",
    firstName: "Amadou",
    lastName: "Diallo",
    birthday: "1995-03-12",
    countryOfOrigin: "Senegal",
    address: "Via Padova 220, Milano",
    phone: "+39 333 5544001",
    workingPermit: true,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma scuola secondaria - Dakar, Senegal (2014)",
      "Corso italiano A2 - CPIA Milano (2023)",
    ],
    workExperience: [
      "Aiuto cuoco - Trattoria da Mario, Milano (2023-2024)",
      "Magazziniere - cooperativa logistica Dakar (2018-2022)",
    ],
    skillsAndCompetences: [
      "Cucina mediterranea base",
      "Lavoro in team multietnico",
      "Resistenza fisica",
      "HACCP base",
    ],
    language: "Francese",
    additionalLanguages: ["Wolof", "Italiano A2", "Inglese B1"],
    italianLevel: "A2",
    desiredJob: "Aiuto cuoco o magazziniere",
    partTimePreference: false,
    preferredLocation: "Milano e hinterland",
    jobConstraints: "No turni notturni durante Ramadan",
    hasDesiredJobExperience: "Sì, 1 anno",
    sourceOrganization: "Cooperativa La Strada - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-na-002",
    firstName: "Karim",
    lastName: "El Mansouri",
    birthday: "1988-09-04",
    countryOfOrigin: "Marocco",
    address: "Via Settembrini 11, Milano",
    phone: "+39 340 6677001",
    workingPermit: true,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma scuola tecnica - Casablanca, Marocco (2007)",
      "Conversione patente C in Italia (2018)",
    ],
    workExperience: [
      "Autista patente C - Trasporti Lombardi, Milano (2019-2024)",
      "Magazziniere - Mercato Ortofrutticolo Casablanca (2010-2017)",
    ],
    skillsAndCompetences: [
      "Guida camion fino 7,5t",
      "Carico e scarico",
      "Conoscenza Milano e provincia",
      "Italiano fluente",
    ],
    language: "Arabo",
    additionalLanguages: ["Francese", "Italiano B2"],
    italianLevel: "B2",
    desiredJob: "Autista patente C",
    partTimePreference: false,
    preferredLocation: "Milano e hinterland",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 5 anni",
    sourceOrganization: "Cooperativa La Strada - WhatsApp",
    channel: "whatsapp",
  },
  {
    externalId: "seed-na-003",
    firstName: "Fatima",
    lastName: "Ben Salem",
    birthday: "1992-11-22",
    countryOfOrigin: "Tunisia",
    address: "Via dei Mille 14, Modena",
    phone: "+39 327 8899002",
    workingPermit: true,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: null,
    educationAndTraining: [
      "Diploma sartoria - Tunisi (2011)",
      "Corso italiano B1 - CPIA Modena (2022)",
    ],
    workExperience: [
      "Addetta pulizie - Impresa di pulizie Modenese (2019-2024)",
      "Sarta - laboratorio artigianale Tunisi (2012-2018)",
    ],
    skillsAndCompetences: [
      "Pulizie civili e industriali",
      "Uso prodotti e DPI",
      "Cucito e piccole riparazioni",
      "Affidabilità e puntualità",
    ],
    language: "Arabo",
    additionalLanguages: ["Francese", "Italiano B1"],
    italianLevel: "B1",
    desiredJob: "Addetta pulizie",
    partTimePreference: true,
    preferredLocation: "Modena città",
    jobConstraints: "Non disponibile venerdì pomeriggio",
    hasDesiredJobExperience: "Sì, 5 anni",
    sourceOrganization: "Cooperativa Modena Lavoro - WhatsApp",
    channel: "whatsapp",
  },
  {
    externalId: "seed-na-004",
    firstName: "Youssef",
    lastName: "Khaled",
    birthday: "1990-06-15",
    countryOfOrigin: "Egitto",
    address: "Via Casilina 320, Roma",
    phone: "+39 351 9988003",
    workingPermit: true,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma ragioneria - Il Cairo (2009)",
      "Corso pizzaiolo - Scuola Italiana Pizzaioli, Roma (2020)",
    ],
    workExperience: [
      "Pizzaiolo - Pizzeria Trastevere, Roma (2020-2024)",
      "Aiuto cuoco - ristorante Il Cairo (2012-2019)",
    ],
    skillsAndCompetences: [
      "Pizza romana e napoletana",
      "Gestione forno a legna",
      "Impasti e lievitazioni",
      "Italiano fluente",
    ],
    language: "Arabo",
    additionalLanguages: ["Inglese B2", "Italiano B2"],
    italianLevel: "B2",
    desiredJob: "Pizzaiolo o aiuto cuoco",
    partTimePreference: false,
    preferredLocation: "Roma centro/sud",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 4 anni come pizzaiolo",
    sourceOrganization: "Cooperativa Roma Multietnica - Telegram",
    channel: "telegram",
  },
];

// ---------------------------------------------------------------------------
// 4 E. European candidates
// ---------------------------------------------------------------------------
const eastEuropeans: Seed[] = [
  {
    externalId: "seed-ee-001",
    firstName: "Ionela",
    lastName: "Popescu",
    birthday: "1985-02-19",
    countryOfOrigin: "Romania",
    address: "Via Tiburtina 78, Roma",
    phone: "+39 333 7766004",
    workingPermit: true,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma liceo - Bucarest, Romania (2003)",
      "Corso badante professionale - Roma (2015)",
    ],
    workExperience: [
      "Badante convivente - privato, Roma (2017-2024)",
      "Collaboratrice domestica - varie famiglie, Roma (2008-2017)",
    ],
    skillsAndCompetences: [
      "Assistenza anziani non autosufficienti",
      "Cucina italiana e dietetica",
      "Pulizie domestiche",
      "Italiano fluente",
    ],
    language: "Rumeno",
    additionalLanguages: ["Italiano C1"],
    italianLevel: "C1",
    desiredJob: "Badante o collaboratrice domestica",
    partTimePreference: false,
    preferredLocation: "Roma e provincia",
    jobConstraints: "Preferenza convivenza",
    hasDesiredJobExperience: "Sì, oltre 15 anni",
    sourceOrganization: "Cooperativa Roma Solidale - WhatsApp",
    channel: "whatsapp",
  },
  {
    externalId: "seed-ee-002",
    firstName: "Andrii",
    lastName: "Kovalenko",
    birthday: "1993-04-08",
    countryOfOrigin: "Ucraina",
    address: "Via Brescia 9, Bergamo",
    phone: "+39 340 5544005",
    workingPermit: true,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma istituto tecnico - Kiev (2012)",
      "Corso italiano A2 - CPIA Bergamo (2023)",
    ],
    workExperience: [
      "Operaio metalmeccanico - Officina Bergamo (2023-2024)",
      "Saldatore - cantiere navale Odessa (2014-2022)",
    ],
    skillsAndCompetences: [
      "Saldatura ad elettrodo e MIG",
      "Carpenteria leggera",
      "Lettura disegni tecnici",
      "Patentino muletto (Ucraina)",
    ],
    language: "Ucraino",
    additionalLanguages: ["Russo", "Italiano A2", "Inglese A2"],
    italianLevel: "A2",
    desiredJob: "Saldatore o operaio metalmeccanico",
    partTimePreference: false,
    preferredLocation: "Bergamo e Brescia",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 8 anni",
    sourceOrganization: "Caritas Bergamo - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-ee-003",
    firstName: "Magdalena",
    lastName: "Nowak",
    birthday: "1990-07-01",
    countryOfOrigin: "Polonia",
    address: "Via Zara 5, Verona",
    phone: "+39 327 6677006",
    workingPermit: true,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma liceo economico - Cracovia (2009)",
      "Corso barista - Verona (2018)",
    ],
    workExperience: [
      "Cameriera/barista - Caffè Centrale Verona (2019-2024)",
      "Cameriera estiva - lago di Garda (2014-2018)",
    ],
    skillsAndCompetences: [
      "Servizio bar e caffetteria",
      "Caffè espresso e cappuccini",
      "Servizio tavoli",
      "Inglese fluente per turisti",
    ],
    language: "Polacco",
    additionalLanguages: ["Inglese C1", "Italiano B2", "Tedesco A2"],
    italianLevel: "B2",
    desiredJob: "Barista o cameriera",
    partTimePreference: true,
    preferredLocation: "Verona e lago di Garda",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 6 anni",
    sourceOrganization: "Cooperativa Veneto Multietnico - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-ee-004",
    firstName: "Petar",
    lastName: "Stoyanov",
    birthday: "1982-12-11",
    countryOfOrigin: "Bulgaria",
    address: "Via Mecenate 84, Milano",
    phone: "+39 339 1122007",
    workingPermit: true,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma istituto autotrasporti - Sofia (2001)",
      "CQC merci - rinnovo Italia 2023",
    ],
    workExperience: [
      "Autista internazionale - Trasporti Bulgaria-UE (2010-2024)",
    ],
    skillsAndCompetences: [
      "Autoarticolato e bilico",
      "Tratte internazionali UE",
      "Cronotachigrafo digitale",
      "Inglese tecnico per dogane",
    ],
    language: "Bulgaro",
    additionalLanguages: ["Russo", "Italiano B1", "Inglese B1"],
    italianLevel: "B1",
    desiredJob: "Autista patente C+E",
    partTimePreference: false,
    preferredLocation: "Milano, disponibile trasferte UE",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 14 anni",
    sourceOrganization: "Cooperativa Milano Trasporti - WhatsApp",
    channel: "whatsapp",
  },
];

// ---------------------------------------------------------------------------
// 4 S. American candidates
// ---------------------------------------------------------------------------
const southAmericans: Seed[] = [
  {
    externalId: "seed-sa-001",
    firstName: "Maria",
    lastName: "Gonzalez",
    birthday: "1987-08-30",
    countryOfOrigin: "Perù",
    address: "Via Padova 88, Milano",
    phone: "+39 333 8899008",
    workingPermit: true,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma liceo - Lima, Perù (2005)",
      "Corso badante - Milano (2017)",
    ],
    workExperience: [
      "Badante convivente - privato, Milano (2018-2024)",
      "Collaboratrice domestica - Lima (2008-2016)",
    ],
    skillsAndCompetences: [
      "Assistenza anziani con Alzheimer",
      "Cucina italiana e sudamericana",
      "Pulizie casa",
      "Italiano fluente",
    ],
    language: "Spagnolo",
    additionalLanguages: ["Italiano C1"],
    italianLevel: "C1",
    desiredJob: "Badante",
    partTimePreference: false,
    preferredLocation: "Milano",
    jobConstraints: "Preferenza convivenza",
    hasDesiredJobExperience: "Sì, 6 anni",
    sourceOrganization: "Cooperativa Milano Multietnica - WhatsApp",
    channel: "whatsapp",
  },
  {
    externalId: "seed-sa-002",
    firstName: "Carlos",
    lastName: "Rodriguez",
    birthday: "1991-05-17",
    countryOfOrigin: "Venezuela",
    address: "Via Marghera 22, Genova",
    phone: "+39 340 9988009",
    workingPermit: true,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma scuola tecnica - Caracas, Venezuela (2010)",
      "Corso italiano B1 - CPIA Genova (2022)",
    ],
    workExperience: [
      "Magazziniere/scaffalista - Esselunga Genova (2022-2024)",
      "Operaio - fabbrica componenti elettrici Caracas (2012-2020)",
    ],
    skillsAndCompetences: [
      "Rifornimento scaffali GDO",
      "Uso transpallet manuale",
      "Inventario e controllo scadenze",
      "Italiano B1 in miglioramento",
    ],
    language: "Spagnolo",
    additionalLanguages: ["Italiano B1", "Inglese A2"],
    italianLevel: "B1",
    desiredJob: "Scaffalista o magazziniere",
    partTimePreference: false,
    preferredLocation: "Genova",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, 2 anni in Italia",
    sourceOrganization: "Cooperativa Liguria Insieme - Telegram",
    channel: "telegram",
  },
  {
    externalId: "seed-sa-003",
    firstName: "Lucia",
    lastName: "Vargas",
    birthday: "1995-10-25",
    countryOfOrigin: "Ecuador",
    address: "Via Casilina 410, Roma",
    phone: "+39 327 7788010",
    workingPermit: true,
    meanOfTransport: "Mezzi pubblici",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma scuola secondaria - Quito (2013)",
      "Corso OSS - Roma (2021)",
    ],
    workExperience: [
      "OSS - Casa di riposo Aurelia, Roma (2022-2024)",
      "Babysitter e collaboratrice domestica - Roma (2017-2022)",
    ],
    skillsAndCompetences: [
      "Assistenza anziani",
      "Igiene e mobilizzazione persona",
      "Compilazione cartelle",
      "Italiano fluente",
    ],
    language: "Spagnolo",
    additionalLanguages: ["Italiano C1"],
    italianLevel: "C1",
    desiredJob: "OSS o badante",
    partTimePreference: false,
    preferredLocation: "Roma ovest",
    jobConstraints: "Disponibile turni notturni",
    hasDesiredJobExperience: "Sì, 3 anni",
    sourceOrganization: "Cooperativa Roma Multietnica - WhatsApp",
    channel: "whatsapp",
  },
  {
    externalId: "seed-sa-004",
    firstName: "Diego",
    lastName: "Fernandez",
    birthday: "1989-02-08",
    countryOfOrigin: "Argentina",
    address: "Via Settembrini 4, Napoli",
    phone: "+39 351 6677011",
    workingPermit: true,
    meanOfTransport: "Auto propria",
    drivingLicense: true,
    educationAndTraining: [
      "Diploma scuola alberghiera - Buenos Aires (2008)",
    ],
    workExperience: [
      "Macellaio - Macelleria Sant'Anna, Napoli (2020-2024)",
      "Macellaio/grigliatore - parrilla Buenos Aires (2010-2019)",
    ],
    skillsAndCompetences: [
      "Sezionamento carni rosse",
      "Tecnica grill argentina (asado)",
      "Disosso e preparazione tagli",
      "Italiano madrelingua",
    ],
    language: "Spagnolo",
    additionalLanguages: ["Italiano (madrelingua famiglia)", "Inglese A2"],
    italianLevel: "Madrelingua",
    desiredJob: "Macellaio o grigliatore",
    partTimePreference: false,
    preferredLocation: "Napoli",
    jobConstraints: null,
    hasDesiredJobExperience: "Sì, oltre 12 anni",
    sourceOrganization: "Cooperativa Napoli Multietnica - Telegram",
    channel: "telegram",
  },
];

const ALL: Seed[] = [...italians, ...northAfricans, ...eastEuropeans, ...southAmericans];

function deriveChannel(s: string): "telegram" | "whatsapp" {
  return s.toLowerCase().includes("whatsapp") ? "whatsapp" : "telegram";
}

async function main() {
  const targetPoolSlug = process.env["TARGET_POOL_SLUG"] ?? "159244";

  const pool = await prisma.pool.findUnique({
    where: { slug: targetPoolSlug },
    select: { id: true, name: true, slug: true },
  });
  if (!pool) {
    throw new Error(
      `Nessun pool trovato con slug=${targetPoolSlug}. ` +
        `Override con TARGET_POOL_SLUG=<valore>.`,
    );
  }
  console.log(
    `Seeding ${ALL.length} candidati nel pool "${pool.name}" (slug ${pool.slug})`,
  );

  for (const s of ALL) {
    const data = {
      first_name: s.firstName,
      last_name: s.lastName,
      birthday: s.birthday,
      country: s.countryOfOrigin,
      address: s.address,
      phone: s.phone,
      working_permit: s.workingPermit,
      transport: s.meanOfTransport,
      driving_license: s.drivingLicense,
      education_and_training: s.educationAndTraining,
      work_experience: s.workExperience,
      skills_and_competences: s.skillsAndCompetences,
      language: s.language,
      additional_languages: s.additionalLanguages,
      italian_level: s.italianLevel,
      job_preferences: {
        preferred_job: s.desiredJob,
        part_time_preference: s.partTimePreference,
        preferred_location: s.preferredLocation,
        constraints: s.jobConstraints,
        has_desired_job_experience: s.hasDesiredJobExperience,
      },
      source_organization: s.sourceOrganization,
      last_updated: new Date().toISOString(),
    };

    const rawPayload = {
      key: s.externalId,
      externalKey: pool.slug,
      data,
    };

    const input = {
      externalId: s.externalId,
      poolId: pool.id,
      firstName: s.firstName,
      lastName: s.lastName,
      birthday: s.birthday,
      countryOfOrigin: s.countryOfOrigin,
      address: s.address,
      phone: s.phone,
      workingPermit: s.workingPermit,
      meanOfTransport: s.meanOfTransport,
      drivingLicense: s.drivingLicense,
      educationAndTraining: s.educationAndTraining,
      workExperience: s.workExperience,
      skillsAndCompetences: s.skillsAndCompetences,
      language: s.language,
      additionalLanguages: s.additionalLanguages,
      italianLevel: s.italianLevel,
      desiredJob: s.desiredJob,
      partTimePreference: s.partTimePreference,
      preferredLocation: s.preferredLocation,
      jobConstraints: s.jobConstraints,
      hasDesiredJobExperience: s.hasDesiredJobExperience,
      interviewLanguage: s.language,
      sourceOrganization: s.sourceOrganization,
      channel: deriveChannel(s.sourceOrganization),
      rawPayload,
      sourceUpdatedAt: new Date(),
    };

    const c = await prisma.candidate.upsert({
      where: {
        poolId_externalId: {
          poolId: pool.id,
          externalId: s.externalId,
        },
      },
      create: input,
      update: input,
      select: { id: true, externalId: true, firstName: true, lastName: true },
    });
    console.log(`  ✓ ${c.externalId}  ${c.firstName} ${c.lastName}  (${c.id})`);
  }

  const total = await prisma.candidate.count({
    where: { poolId: pool.id },
  });
  console.log(`\nDone. Totale candidati nel pool: ${total}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
