import type { SectionDef, QuestionDef } from "./types";

export const ASSESSMENT_SECTIONS: SectionDef[] = [
  {
    id: "s-cog",
    title: "Come risolvi i problemi",
    order: 1,
    questions: [
      {
        id: "q1",
        component: "single_choice",
        label: "Problem solving",
        text: "Hai un problema che non hai mai affrontato prima. Cosa fai di solito?",
        target: { kind: "profile", path: "cognitive.q1" },
        options: [
          { value: "analitico", label: "Cerco di capire bene la situazione prima di muovermi — analizzo, poi agisco" },
          { value: "pratico", label: "Provo subito qualcosa e vedo cosa succede — imparo facendo" },
          { value: "relazionale", label: "Chiedo a qualcuno che ne sa più di me — mi fido dell'esperienza altrui" },
          { value: "intuitivo", label: "Mi fido dell'istinto e dell'esperienza passata — spesso funziona" },
        ],
      },
      {
        id: "q2",
        component: "single_choice",
        label: "Dettaglio vs. visione",
        text: "Quando lavori su qualcosa, cosa ti viene più naturale?",
        target: { kind: "profile", path: "cognitive.q2" },
        options: [
          { value: "dettaglio", label: "Controllare ogni dettaglio finché non è perfetto" },
          { value: "visione", label: "Tenere chiaro il quadro generale" },
          { value: "entrambi", label: "Alterno: prima il tutto, poi i dettagli" },
          { value: "dipende", label: "Dipende dal tipo di lavoro" },
        ],
      },
      {
        id: "q3",
        component: "scale",
        label: "Numeri e logica",
        text: "Durante la giornata, quanto spesso ti trovi a fare calcoli, stime o confronti tra numeri?",
        target: { kind: "profile", path: "cognitive.numeracy" },
        scale: { min: 1, max: 5, default: 3, labelMin: "Mai, evito i numeri", labelMax: "Continuamente, mi viene naturale" },
      },
      {
        id: "q4",
        component: "single_choice",
        label: "Gestione dell'imprevisto",
        text: "Stai lavorando e arriva un imprevisto che cambia tutto. Come ti senti di solito?",
        target: { kind: "profile", path: "cognitive.q4" },
        options: [
          { value: "fastidio", label: "Fastidio — preferisco che le cose vadano come pianificato" },
          { value: "neutro", label: "Neutro — mi adatto senza problemi" },
          { value: "stimolo", label: "Energizzato — gli imprevisti mi stimolano" },
          { value: "dipende", label: "Dipende da quanto è grave" },
        ],
      },
    ],
  },
  {
    id: "s-exp",
    title: "Esperienze lavorative",
    order: 2,
    questions: [
      {
        id: "esperienze",
        component: "repeatable_group",
        label: "Esperienze lavorative",
        text: "Aggiungi le tue esperienze lavorative",
        target: { kind: "profile", path: "experience.entries" },
        fields: [
          {
            id: "ruolo",
            component: "text",
            label: "Che lavoro / ruolo era?",
            target: { kind: "column", field: "workExperience", strategy: "append" },
            placeholder: "Es. cameriere, idraulico, receptionist, magazziniere...",
          },
          {
            id: "durata",
            component: "select",
            label: "Per quanto tempo?",
            target: { kind: "column", field: "workExperience", strategy: "append" },
            selectOptions: ["Meno di 6 mesi", "6 mesi – 2 anni", "2 – 5 anni", "Più di 5 anni"],
          },
          {
            id: "attivita",
            component: "textarea",
            label: "Cosa facevi concretamente ogni giorno?",
            target: { kind: "column", field: "workExperience", strategy: "append" },
            placeholder: "Es. gestivo i clienti al banco, riparavo impianti, preparavo i piatti...",
          },
          {
            id: "skills_universali",
            component: "multi_choice",
            label: "Competenze trasversali sviluppate in questo ruolo",
            target: { kind: "column", field: "skillsAndCompetences", strategy: "append" },
            options: [
              { value: "Gestione del cliente", label: "Gestione del cliente" },
              { value: "Lavoro manuale", label: "Lavoro manuale" },
              { value: "Organizzazione e pianificazione", label: "Organizzazione e pianificazione" },
              { value: "Gestione fornitori", label: "Gestione fornitori" },
              { value: "Formazione di altri", label: "Formazione di altri" },
              { value: "Controllo qualità", label: "Controllo qualità" },
              { value: "Vendita e negoziazione", label: "Vendita e negoziazione" },
              { value: "Risoluzione problemi tecnici", label: "Risoluzione problemi tecnici" },
              { value: "Gestione emergenze", label: "Gestione emergenze" },
              { value: "Strumenti digitali", label: "Strumenti digitali" },
              { value: "Lavoro in team", label: "Lavoro in team" },
              { value: "Lavoro in autonomia", label: "Lavoro in autonomia" },
              { value: "Comunicazione scritta", label: "Comunicazione scritta" },
              { value: "Contabilità base", label: "Contabilità base" },
              { value: "Cura della persona", label: "Cura della persona" },
              { value: "Lavoro fisico", label: "Lavoro fisico" },
            ],
          },
          {
            id: "skills_specifiche",
            component: "text",
            label: "Competenze specifiche di questo lavoro (scrivi tu)",
            target: { kind: "column", field: "skillsAndCompetences", strategy: "append" },
            placeholder: "Es. saldatura, pasticceria, check-in alberghiero, taglio capelli...",
          },
          {
            id: "gradimento",
            component: "scale",
            label: "Quanto ti piaceva questo lavoro?",
            target: { kind: "profile", path: "experience.gradimento" },
            scale: { min: 1, max: 5, default: 3, labelMin: "Per niente", labelMax: "Moltissimo" },
          },
        ],
      },
      {
        id: "titolo_studio",
        component: "select",
        label: "Titolo di studio più alto",
        text: "Titolo di studio più alto",
        target: { kind: "column", field: "educationAndTraining", strategy: "append" },
        selectOptions: [
          "Licenza media",
          "Diploma professionale / qualifica",
          "Diploma di scuola superiore",
          "Laurea triennale",
          "Laurea magistrale / specialistica",
          "Master o dottorato",
          "Preferisco non dirlo",
        ],
      },
      {
        id: "corsi",
        component: "textarea",
        label: "Corsi, certificazioni o formazione professionale rilevante",
        text: "Corsi, certificazioni o formazione professionale rilevante",
        target: { kind: "column", field: "educationAndTraining", strategy: "append" },
        placeholder: "Es. corso di cucina, patentino elettrico, certificazione sicurezza, corso lingue...",
      },
    ],
  },
  {
    id: "s-exec",
    title: "Come lavori",
    order: 3,
    questions: [
      {
        id: "q5",
        component: "single_choice",
        label: "Manualità",
        text: "Hai mai riparato, costruito, montato o smontato qualcosa con le mani? Come ti sei trovato?",
        target: { kind: "profile", path: "exec.q5" },
        options: [
          { value: "forte", label: "Sì, mi viene naturale e mi piace molto — è uno dei miei punti di forza" },
          { value: "medio", label: "Sì, ma non è il mio forte — faccio fatica o mi piace poco" },
          { value: "raro", label: "Raramente mi sono cimentato in questo" },
          { value: "no", label: "No, non ho mai lavorato con le mani in modo significativo" },
        ],
      },
      {
        id: "q6",
        component: "single_choice",
        label: "Organizzazione",
        text: "Pensa all'ultima volta che hai organizzato qualcosa di complesso. Come ti sei comportato?",
        target: { kind: "profile", path: "exec.q6" },
        options: [
          { value: "lista", label: "Lista dettagliata e piano passo per passo" },
          { value: "memoria", label: "A memoria, una cosa alla volta" },
          { value: "coordinato", label: "Ho coinvolto altri e coordinato il gruppo" },
          { value: "improv", label: "Ho improvvisato, risolvendo man mano" },
        ],
      },
      {
        id: "q7a",
        component: "scale",
        label: "Comunicazione — efficacia",
        text: "Quanto ti riesce facile spiegare qualcosa a qualcuno che non ne sa niente?",
        target: { kind: "profile", path: "exec.q7a" },
        scale: { min: 1, max: 5, default: 3, labelMin: "Faccio molta fatica", labelMax: "È una delle mie cose migliori" },
      },
      {
        id: "q7b",
        component: "single_choice",
        label: "Comunicazione — stile",
        text: "In quale forma comunichi meglio?",
        target: { kind: "profile", path: "exec.q7b" },
        options: [
          { value: "parlato", label: "Di persona, parlando" },
          { value: "scritto", label: "Per iscritto" },
          { value: "dimostrando", label: "Mostrando come si fa" },
          { value: "visivo", label: "Con schemi o esempi visivi" },
        ],
      },
      {
        id: "q8",
        component: "single_choice",
        label: "Attività fisica",
        text: "Come preferisci passare la tua giornata lavorativa dal punto di vista fisico?",
        target: { kind: "profile", path: "exec.q8" },
        options: [
          { value: "fisico", label: "In movimento — stare fermo mi pesa" },
          { value: "sedentario", label: "Prevalentemente seduto" },
          { value: "misto", label: "Misto — va bene entrambi" },
          { value: "indiff", label: "Non ho preferenze forti" },
        ],
      },
    ],
  },
  {
    id: "s-rel",
    title: "Come ti relazioni con le persone",
    order: 4,
    questions: [
      {
        id: "q9",
        component: "single_choice",
        label: "Energia e persone",
        text: "Dopo una lunga giornata passata a lavorare con molte persone, come ti senti di solito?",
        target: { kind: "profile", path: "relational.q9" },
        options: [
          { value: "ricaricato", label: "Energizzato — le persone mi caricano" },
          { value: "esausto", label: "Esausto — ho bisogno di stare un po' da solo per ricaricarmi" },
          { value: "dipende", label: "Dipende molto dalle persone e dal tipo di interazione" },
        ],
      },
      {
        id: "q10",
        component: "single_choice",
        label: "Ruolo nel gruppo",
        text: "Quando lavori con altre persone, cosa ti riesce più naturalmente?",
        target: { kind: "profile", path: "relational.q10" },
        options: [
          { value: "guida", label: "Guidare, motivare, dare una direzione al gruppo" },
          { value: "supporto", label: "Ascoltare, supportare, aiutare gli altri a risolvere problemi" },
          { value: "insegna", label: "Spiegare, insegnare, trasferire quello che so" },
          { value: "coordina", label: "Coordinare, organizzare, tenere tutti allineati" },
          { value: "solo", label: "Preferisco lavorare da solo e interfacciarmi il meno possibile" },
        ],
      },
      {
        id: "q11",
        component: "single_choice",
        label: "Conflitto",
        text: "Se c'è tensione o disaccordo tra persone con cui lavori, cosa fai?",
        target: { kind: "profile", path: "relational.q11" },
        options: [
          { value: "media", label: "Intervengo per trovare un accordo" },
          { value: "evita", label: "Evito, preferisco non intromettermi" },
          { value: "diretto", label: "Dico la mia posizione, anche se crea attrito" },
          { value: "attende", label: "Aspetto che si risolva da solo" },
        ],
      },
      {
        id: "q12",
        component: "single_choice",
        label: "Scenario",
        text: "Immagina una giornata libera da passare come vuoi. Quale di queste ti attira di più?",
        target: { kind: "profile", path: "relational.q12" },
        options: [
          { value: "aiuto", label: "Aiutare qualcuno a risolvere un problema pratico" },
          { value: "solo", label: "Lavorare da solo su qualcosa che mi appassiona" },
          { value: "gruppo", label: "Organizzare un'attività con un gruppo" },
          { value: "esplora", label: "Esplorare un posto nuovo o imparare qualcosa" },
        ],
      },
    ],
  },
  {
    id: "s-int",
    title: "Interessi e motivatori",
    order: 5,
    questions: [
      {
        id: "q13",
        component: "multi_choice",
        label: "Attività che ti hanno dato soddisfazione",
        text: "Quali di queste hai fatto almeno una volta con una sensazione positiva?",
        hint: "Seleziona tutto ciò che si applica — anche fuori dal lavoro vero e proprio.",
        target: { kind: "profile", path: "interests.activities" },
        options: [
          { value: "Costruire o riparare con le mani", label: "Costruire o riparare con le mani" },
          { value: "Prendermi cura di qualcuno", label: "Prendermi cura di qualcuno" },
          { value: "Organizzare un evento o gruppo", label: "Organizzare un evento o gruppo" },
          { value: "Creare qualcosa di visivo", label: "Creare qualcosa di visivo" },
          { value: "Spiegare o insegnare", label: "Spiegare o insegnare" },
          { value: "Risolvere problemi tecnici o logici", label: "Risolvere problemi tecnici o logici" },
          { value: "Vendere o convincere", label: "Vendere o convincere" },
          { value: "Cucinare o trasformare materiali", label: "Cucinare o trasformare materiali" },
          { value: "Lavorare all'aperto o con la natura", label: "Lavorare all'aperto o con la natura" },
          { value: "Scrivere o comunicare idee", label: "Scrivere o comunicare idee" },
          { value: "Usare strumenti digitali o software", label: "Usare strumenti digitali o software" },
          { value: "Gestire numeri o conti", label: "Gestire numeri o conti" },
        ],
      },
      {
        id: "q14",
        component: "single_choice",
        label: "Motivatore primario",
        text: "Cosa ti fa sentire di aver fatto un buon lavoro?",
        target: { kind: "profile", path: "interests.q14" },
        options: [
          { value: "risultato", label: "Ho risolto un problema concreto e si vede il risultato con i miei occhi" },
          { value: "relazione", label: "Qualcuno mi ha ringraziato o si è sentito meglio grazie a me" },
          { value: "apprendimento", label: "Ho imparato qualcosa di nuovo o migliorato una mia competenza" },
          { value: "estetica", label: "Ho creato qualcosa di bello, originale o ben fatto" },
          { value: "precisione", label: "Ho rispettato i tempi e i requisiti e ho fatto tutto per bene" },
        ],
      },
      {
        id: "q15",
        component: "scale",
        label: "Autonomia creativa",
        text: "Quanto è importante per te poter fare le cose a modo tuo o esprimere idee originali?",
        target: { kind: "profile", path: "interests.q15" },
        scale: { min: 1, max: 5, default: 3, labelMin: "Per niente — preferisco istruzioni chiare", labelMax: "Moltissimo — soffro senza autonomia" },
      },
      {
        id: "q16",
        component: "multi_choice",
        label: "Contesto e vincoli reali",
        text: "Quali di queste situazioni descrivono la tua condizione attuale?",
        hint: "Seleziona tutte quelle che si applicano — ci servono per darti suggerimenti realistici.",
        target: { kind: "column", field: "jobConstraints", strategy: "set" },
        options: [
          { value: "Disponibile a spostarmi per lavoro", label: "Disponibile a spostarmi per lavoro" },
          { value: "Preferisco lavorare vicino a casa", label: "Preferisco lavorare vicino a casa" },
          { value: "Ho esigenze di orario fisso", label: "Ho esigenze di orario fisso" },
          { value: "Posso lavorare su turni o orari irregolari", label: "Posso lavorare su turni o orari irregolari" },
          { value: "Disposto a fare formazione per cambiare settore", label: "Disposto a fare formazione per cambiare settore" },
          { value: "Ho una competenza specifica da valorizzare", label: "Ho una competenza specifica da valorizzare" },
          { value: "Prima esperienza lavorativa", label: "Prima esperienza lavorativa" },
          { value: "Voglio cambiare settore", label: "Voglio cambiare settore" },
        ],
      },
    ],
  },
];

export function allQuestions(): import("./types").QuestionDef[] {
  return ASSESSMENT_SECTIONS.flatMap((s) => s.questions);
}
