/**
 * One-shot builder: downloads the ISTAT "Elenco dei comuni italiani" CSV
 * and emits src/lib/geo/italy-admin.ts.
 *
 * Run: pnpm tsx scripts/build-italy-admin.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const ISTAT_CSV_URL =
  "https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.csv";

interface Row {
  municipality: string;
  province: string;
  provinceCode: string;
  region: string;
}

/**
 * Minimal RFC 4180-ish CSV parser for `;`-delimited data with quoted fields
 * that can contain embedded newlines. Returns rows as string[] arrays.
 */
function parseCsvRows(text: string, delimiter = ";"): string[][] {
  const rows: string[][] = [];
  let field = "";
  let row: string[] = [];
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += ch;
      }
    } else {
      if (ch === '"') {
        inQuotes = true;
      } else if (ch === delimiter) {
        row.push(field);
        field = "";
      } else if (ch === "\n" || ch === "\r") {
        // consume \r\n as one line break
        if (ch === "\r" && text[i + 1] === "\n") i++;
        row.push(field);
        field = "";
        // skip fully-empty lines
        if (row.length > 1 || row[0] !== "") {
          rows.push(row);
        }
        row = [];
      } else {
        field += ch;
      }
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    if (row.length > 1 || row[0] !== "") rows.push(row);
  }
  return rows;
}

function normalizeHeader(h: string): string {
  return h.replace(/\s+/g, " ").trim().toLowerCase();
}

function parseCsv(text: string): Row[] {
  const rows = parseCsvRows(text, ";");
  const headerRow = rows[0];
  if (!headerRow) throw new Error("Empty CSV");
  const header = headerRow.map(normalizeHeader);
  const idx = {
    region: header.findIndex(
      (h) => h.includes("denominazione regione") || h === "regione",
    ),
    province: header.findIndex((h) =>
      h.startsWith("denominazione dell'unità territoriale"),
    ),
    provinceCode: header.findIndex((h) => h.includes("sigla automobilistica")),
    municipality: header.findIndex((h) => h.startsWith("denominazione in italiano")),
  };
  if (Object.values(idx).some((i) => i < 0)) {
    throw new Error(`Could not locate required columns. Header: ${header.join(" | ")}`);
  }
  const out: Row[] = [];
  for (const cells of rows.slice(1)) {
    const municipality = cells[idx.municipality]?.trim();
    const province = cells[idx.province]?.trim();
    const provinceCode = cells[idx.provinceCode]?.trim() ?? "";
    const region = cells[idx.region]?.trim();
    if (municipality && province && region) {
      out.push({ municipality, province, provinceCode, region });
    }
  }
  return out;
}

async function main() {
  const res = await fetch(ISTAT_CSV_URL);
  if (!res.ok) throw new Error(`ISTAT fetch failed: ${res.status}`);
  const buf = await res.arrayBuffer();
  const text = new TextDecoder("iso-8859-1").decode(buf);
  const rows = parseCsv(text);
  if (rows.length < 7000) throw new Error(`Too few rows parsed: ${rows.length}`);

  const file = `// AUTO-GENERATED by scripts/build-italy-admin.ts — do not edit manually.
export interface ItalyAdminRow {
  municipality: string;
  province: string;
  provinceCode: string;
  region: string;
}

export const ITALY_ADMIN: readonly ItalyAdminRow[] = ${JSON.stringify(rows, null, 2)} as const;
`;
  const out = resolve(process.cwd(), "src/lib/geo/italy-admin.ts");
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, file, "utf8");
  console.log(`Wrote ${rows.length} rows to ${out}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
